# Public RSS/Atom sources (US & Canada focus). Add/remove feeds here.
# NOTE: These URLs are publicly available endpoints; no auth.

SOURCES = {
    "banking_regulatory": [
        {
            "id": "fed_press",
            "name": "Federal Reserve — Press Releases",
            "region": "US",
            "type": "regulator",
            "weight": 1.2,
            "url": "https://www.federalreserve.gov/feeds/press_all.xml",
        },
        {
            "id": "fdic_press",
            "name": "FDIC — Press Releases",
            "region": "US",
            "type": "regulator",
            "weight": 1.2,
            "url": "https://www.fdic.gov/news/press-releases/feed",
        },
        {
            "id": "occ_news",
            "name": "OCC — News",
            "region": "US",
            "type": "regulator",
            "weight": 1.15,
            "url": "https://www.occ.gov/rss/news.xml",
        },
        {
            "id": "cfpb_news",
            "name": "CFPB — Newsroom",
            "region": "US",
            "type": "regulator",
            "weight": 1.15,
            "url": "https://www.consumerfinance.gov/about-us/newsroom/feed/",
        },
        {
            "id": "osfi",
            "name": "OSFI — Updates (Canada)",
            "region": "CA",
            "type": "regulator",
            "weight": 1.25,
            "url": "https://www.osfi-bsif.gc.ca/Eng/rss.xml",
        },
        {
            "id": "bank_of_canada",
            "name": "Bank of Canada — News",
            "region": "CA",
            "type": "regulator",
            "weight": 1.2,
            "url": "https://www.bankofcanada.ca/feed/",
        },
        {
            "id": "sec_edgar",
            "name": "SEC EDGAR — Current Filings",
            "region": "US",
            "type": "filings",
            "weight": 1.1,
            "url": "https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&CIK=&type=&company=&owner=include&count=40&output=atom",
        },
    ],
    "technology": [
        {
            "id": "the_verge",
            "name": "The Verge — Tech",
            "region": "NA",
            "type": "media",
            "weight": 1.0,
            "url": "https://www.theverge.com/rss/index.xml",
        },
        {
            "id": "arstechnica",
            "name": "Ars Technica",
            "region": "NA",
            "type": "media",
            "weight": 1.0,
            "url": "http://feeds.arstechnica.com/arstechnica/index",
        },
        {
            "id": "microsoft_blog",
            "name": "Microsoft Blog",
            "region": "NA",
            "type": "company",
            "weight": 0.95,
            "url": "https://blogs.microsoft.com/feed/",
        },
    ],
    "ai": [
        {
            "id": "mit_tr",
            "name": "MIT Technology Review",
            "region": "NA",
            "type": "media",
            "weight": 1.0,
            "url": "https://www.technologyreview.com/feed/",
        },
        {
            "id": "openai",
            "name": "OpenAI — Blog",
            "region": "NA",
            "type": "company",
            "weight": 0.95,
            "url": "https://openai.com/blog/rss/",
        },
        {
            "id": "nvidia_blog",
            "name": "NVIDIA Blog",
            "region": "NA",
            "type": "company",
            "weight": 0.95,
            "url": "https://blogs.nvidia.com/blog/feed/",
        },
    ],
}
